appname: "recipe2"
layout: "main"
charset: "UTF-8"
port: 80
session: "YAML"
session_dir: "/tmp/dancer-sessions"
template: "template_toolkit"
engines:
    template_toolkit:
        encoding : 'utf8'
        start_tag: '[%'
        stop_tag: '%]'
facebook:
    postback: "http://www.yourapplication.com/facebook/postback/"
    app_id: "XXXXXXXXXXXXXXXX"
    secret: "XXXXXXXXXXXXXXXXXXXXXXXXXXX"

